"""Add school_name field to Student model

Revision ID: 233f6b56ad19
Revises: 3ede185416cc
Create Date: 2026-02-09 14:34:52.267143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233f6b56ad19'
down_revision = '3ede185416cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###
